### PR TITLE
NO_REF: Experimental TFA support.

### PR DESCRIPTION
**Pull request by gdzevo**
I'm not a pro in C++
Please be polite in comments :)

### CODE REVIEW

**Comment by blackjackshellac** [comment]
I managed to get it to compile and it runs but I don't know how to get a prompt for the TFA code.

**Comment by gdzevo** [comment]
@blackjackshellac have you enabled TFA for account?
First login after you enable TFA should be made in foreground (without -d flag).

**Comment by blackjackshellac** [comment]
I used used `ploudcc -u myusername@foo.com -p` and it got stuck at CONNECTING

```
$ pcloudcc -u myusername@foo.com -p
pCloud console client v.2.1.0
Please, enter password

Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING

```
After that nothing happens.

**Comment by blackjackshellac** [comment]
BTW, yes I did enable TFA.  I just used to to reconnect the desktop version of pcloud 1.5.1

**Comment by gdzevo** [comment]
Hmm, that is how it should be:
```
Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
Down: Everything Downloaded| Up: Everything Uploaded, status is TFA_ERROR
two factor authentication - Please, enter password

Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
Down: Everything Downloaded| Up: Everything Uploaded, status is READY
```
Could you please check that you use latest `libpcloudcc_lib.so` and share system information and boost library version that you have used.
I'll try to reproduce this in docker.

**Comment by blackjackshellac** [comment]
Everything looks correct to me,

```
$ ll /usr/local/lib/libpcloudcc_lib.so 
-rwxr-xr-x 1 root root 5514424 May  1 10:34 /usr/local/lib/libpcloudcc_lib.so
$ ll /usr/local/bin/pcloudcc 
-rwxr-xr-x 1 root root 232680 May  1 10:34 /usr/local/bin/pcloudcc
$ ldd /usr/local/bin/pcloudcc 
	linux-vdso.so.1 (0x00007ffc509ab000)
	libpcloudcc_lib.so => /usr/local/lib/libpcloudcc_lib.so (0x00007fe188a68000)
	libboost_system.so.1.66.0 => /lib64/libboost_system.so.1.66.0 (0x00007fe188a61000)
	libboost_program_options.so.1.66.0 => /lib64/libboost_program_options.so.1.66.0 (0x00007fe1889de000)
	libfuse.so.2 => /lib64/libfuse.so.2 (0x00007fe18899d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe18897b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe188961000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe188959000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe1887c1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe18863d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe188622000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe18845c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe188ded000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe188452000)

```

**Comment by gdzevo** [comment]
@blackjackshellac finally compiled with boost 1.66 and it still working.
Which OS you use?

**Comment by blackjackshellac** [comment]
I was on Fedora 29.

**Comment by blackjackshellac** [comment]
I updated to Fedora 30 in the interrim and this is what I see now,

```
pCloud console client v.2.1.0
Please, enter password
Down: Everything Downloaded| Up: Everything Uploaded, status is SCANNING
Down: Everything Downloaded| Up: Everything Uploaded, status is READY
```
But it never asks me for a token ... maybe it's because I was using the desktop client.  I'll try on another machine.

**Comment by blackjackshellac** [comment]
This is what I had to change to get it to compile on my system, can you do a `git apply` to test on your branch,

[pCloudCC_PSYNC_HAS_BUILTIN.zip](https://github.com/pcloudcom/console-client/files/3145967/pCloudCC_PSYNC_HAS_BUILTIN.zip)

**Comment by gdzevo** [comment]
Thank you @blackjackshellac.
Added your diff to separate commit.

**Comment by nikosdion** [comment]
I have tested this PR successfully. Thank you, @gdzevo!

**Comment by jaeichel** [comment]
Thank you @gdzevo - rebased and confirmed that your changes still work.

@pcloudcom can you please review, comment, and merge?

**Comment by gdzevo** [comment]
Closed in favor of rebased PR https://github.com/pcloudcom/console-client/pull/163

**Pull request closed without merging**
